# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: UWAppDev
email: appdev@uw.edu
# For search engines
description: >- # this means to ignore newlines
  The website for the app development club at the University of
  Washington, Seattle.
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
# theme: hematite
remote_theme: personalizedrefrigerator/jekyll-hematite-theme
plugins:
  - jekyll-feed
  - jemoji

favicon_url: /favicon.png

hematite:
  sidebar:
    footer_html: >-
        <span>Est. 2019 <a href="https://huskylink.washington.edu/organization/appdev">at UW Seattle</a></span>
        <a href="https://uwapp.dev/discord">Discord</a>
        <a href="https://github.com/UWAppDev">GitHub</a>
        <a href="https://uwdev.app">Made by Us</a>
    show_settings_btn: true

  # Invert images in dark mode
  auto_invert_imgs: true

  # Set to true to minimize the header by default
  minimize_header: false

  # Date options are as specified here:
  # https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat
  date_format:
    # Short weekday (e.g. Thu for Thursday)
    # weekday: short
    # Long weekday (e.g. Monday)
    weekday: long

    # Use two digits for the month and day
    month: 2-digit
    day: 2-digit

    # The full year
    year: numeric

    parsing:
      # True if the date should be parsed MM/DD/YYYY instead of
      # DD/MM/YYYY
      month_first: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
